baseURL = 'https://hhanh00.github.io/zcash-sync/'
canonifyURLs = true
languageCode = 'en-us'
title = 'Zcash Warp Sync'

theme = "hugo-theme-relearn"

[params]
themeVariant = "blue"
showVisitedLinks = true
disableLandingPageButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]    
unsafe = true
